name: DockerHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main
    tags:
      - '*.*.*'
    paths:
      - '.dockerignore'
      - '.github/workflows/dockerhub.yml'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - '**.go'

jobs:
  multiarch-build:
    strategy:
      matrix:
        base: [alpine, debian]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Get Docker tags for Alpine based image
        if: ${{ matrix.base == 'alpine' }}
        id: docker_meta_alpine
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            nginxproxy/docker-gen
            jwilder/docker-gen
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
      
      - name: Get Docker tags for Debian based image
        if: ${{ matrix.base == 'debian' }}
        id: docker_meta_debian
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            nginxproxy/docker-gen
            jwilder/docker-gen
          tags: |
            type=semver,suffix=-debian,pattern={{version}}
            type=semver,suffix=-debian,pattern={{major}}.{{minor}}
            type=raw,value=debian,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          flavor: latest=false

      - name: Retrieve version
        run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push the Alpine based image
        if: ${{ matrix.base == 'alpine' }}
        id: docker_build_alpine
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.docker_meta_alpine.outputs.tags }}
          labels: ${{ steps.docker_meta_alpine.outputs.labels }}
      
      - name: Build and push the Debian based image
        if: ${{ matrix.base == 'debian' }}
        id: docker_build_debian
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ env.VERSION }}
          file: Dockerfile.debian
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.docker_meta_debian.outputs.tags }}
          labels: ${{ steps.docker_meta_debian.outputs.labels }}

      - name: Alpine based image digest
        if: ${{ matrix.base == 'alpine' }}
        run: echo ${{ steps.docker_build_alpine.outputs.digest }}
      
      - name: Debian based image digest
        if: ${{ matrix.base == 'debian' }}
        run: echo ${{ steps.docker_build_debian.outputs.digest }}